"""Command-line entry point for the LEO residual-learning experiment."""

from __future__ import annotations

from datetime import datetime, timezone
import os
from typing import Optional

import numpy as np

from config import build_arg_parser, config_from_args
from data.dataset import NARXWindowDataset, SequenceWindowDataset
from data.preprocess import (
    build_history_features,
    build_narx_exogenous_features,
    build_static_features,
    build_time_grid,
    combine_target,
    fit_scalers,
    fit_narx_scalers,
    make_noisy_training_observations,
    split_target,
    estimate_orbital_period_sec,
)
from eval.metrics import (
    COMPONENT_LABELS_POS,
    COMPONENT_LABELS_VEL,
    checkpoint_error_summary,
    component_metrics,
    cumulative_vector_rmse,
    improvement_percentage,
)
from eval.plots import (
    plot_3d_orbits,
    plot_error_comparison,
    plot_final_error_bar,
    plot_forecast_residuals,
    plot_noisy_vs_clean_train,
    plot_rmse_over_time,
    plot_rtn_residuals,
    plot_training_history,
)
from orbit.frames import datetime_to_absolutedate, initialize_orekit
from orbit.hpop_prop import propagate_orekit_truth
from orbit.rtn import build_eci_to_rtn_matrices, project_batch_eci_to_rtn, project_batch_rtn_to_eci
from orbit.sgp4_prop import get_tle_epoch_state_gcrf, propagate_sgp4_gcrf
from orbit.tle_io import load_tle_satellite
from train.trainer import (
    autoregressive_rollout,
    narx_autoregressive_rollout,
    narx_teacher_forced_rollout,
    train_model,
)
from utils.io_utils import (
    ensure_output_dirs,
    save_json,
    save_metrics_csv,
    save_npz,
    save_residual_dataframe,
    save_state_dataframe,
)
from utils.logging_utils import log_section, setup_logger
from utils.seed import set_seed


def parse_utc_datetime(value: Optional[str]) -> Optional[datetime]:
    """Parse a UTC datetime string into a timezone-aware datetime."""
    if value is None:
        return None
    text = value.strip().replace("Z", "+00:00")
    dt = datetime.fromisoformat(text)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt


def seq2seq_teacher_forced_train_rollout(
    model,
    device: str,
    static_train: np.ndarray,
    noisy_target_train: np.ndarray,
    config,
    scalers,
) -> np.ndarray:
    """Predict the training segment using teacher-forced history only."""
    predicted = np.zeros_like(noisy_target_train)
    predicted[: config.input_len] = noisy_target_train[: config.input_len]
    cursor = config.input_len
    model.eval()
    import torch

    with torch.no_grad():
        while cursor < len(noisy_target_train):
            hist_start = cursor - config.input_len
            future_end = min(cursor + config.pred_len, len(noisy_target_train))
            hist_features = build_history_features(static_train[hist_start:cursor], noisy_target_train[hist_start:cursor])
            future_cov = static_train[cursor:future_end]
            x_hist = scalers["history"].transform(hist_features)[None, ...].astype(np.float32)
            x_future = scalers["future"].transform(future_cov)[None, ...].astype(np.float32)
            pred_norm = model(
                torch.from_numpy(x_hist).to(device),
                torch.from_numpy(x_future).to(device),
            ).cpu().numpy()[0]
            pred_block = scalers["target"].inverse_transform(pred_norm)
            predicted[cursor:future_end] = pred_block[: future_end - cursor]
            cursor = future_end
    return predicted


def main() -> None:
    parser = build_arg_parser()
    config = config_from_args(parser.parse_args())
    output_dirs = ensure_output_dirs(config.output_dir)
    logger = setup_logger(output_dirs["root"])
    set_seed(config.seed)
    rng = np.random.default_rng(config.seed)

    log_section(logger, "Experiment Setup")
    orekit_context = initialize_orekit(config.orekit_data_path, logger=logger)
    logger.info("TLE initializes the nominal SGP4 orbit through Orekit TLEPropagator.")
    logger.info("Synthetic truth is generated by Orekit NumericalPropagator, initialized from the TLE-epoch SGP4 Cartesian state.")
    logger.info("This synthetic truth is not a real measurement truth orbit.")
    logger.info("All trajectory comparisons are performed in the common inertial frame GCRF.")
    logger.info("Orekit data source: %s", orekit_context["data_path"])
    logger.info(
        "Receiver LLA metadata: lat=%.6f deg, lon=%.6f deg, alt=%.3f m. Current observation model does not enforce station visibility.",
        config.receiver_lat_deg,
        config.receiver_lon_deg,
        config.receiver_alt_m,
    )
    if config.model_name == "narx":
        logger.info(
            "Prediction model: paper-style NARX | input_lags=%d | feedback_lags=%d | hidden_dim=%d | hidden_layers=%d | velocity_input=%s",
            config.narx_input_lags,
            config.narx_feedback_lags,
            config.narx_hidden_dim,
            config.narx_num_hidden_layers,
            config.narx_use_velocity_input,
        )
        if not np.isclose(config.dt_train_sec, config.dt_full_sec):
            logger.warning(
                "NARX is trained with dt_train=%.6f s but rolled out with dt_full=%.6f s. "
                "For one-step NARX this step mismatch often causes near-constant predictions. "
                "Prefer using the same sampling interval for training and forecast.",
                config.dt_train_sec,
                config.dt_full_sec,
            )
        if config.narx_input_lags <= 2 or config.narx_feedback_lags <= 2:
            logger.warning(
                "Current NARX delays are very short (input_lags=%d, feedback_lags=%d). "
                "With only ~400 s observations this often collapses to mean/persistence behavior. "
                "Try 32-128 delays first.",
                config.narx_input_lags,
                config.narx_feedback_lags,
            )
    else:
        logger.info("Prediction model: %s", config.model_name)

    satellite = load_tle_satellite(config.tle_file, config.sat_name)
    scenario_start_utc = parse_utc_datetime(config.scenario_start_utc) or satellite.epoch_utc
    if scenario_start_utc < satellite.epoch_utc:
        raise ValueError(
            f"scenario_start_utc ({scenario_start_utc.isoformat()}) must not be earlier than TLE epoch ({satellite.epoch_utc.isoformat()})."
        )
    scenario_offset_sec = (scenario_start_utc - satellite.epoch_utc).total_seconds()
    logger.info(
        "Satellite: %s | NORAD: %s | TLE epoch UTC: %s | Scenario start UTC: %s",
        satellite.name,
        satellite.norad_id,
        satellite.epoch_utc.isoformat(),
        scenario_start_utc.isoformat(),
    )

    scenario_times_sec = build_time_grid(
        train_duration_sec=config.train_duration_sec,
        total_duration_sec=config.total_duration_sec,
        dt_train_sec=config.dt_train_sec,
        dt_full_sec=config.dt_full_sec,
    )
    sample_times_since_tle_sec = scenario_offset_sec + scenario_times_sec
    train_mask = scenario_times_sec < config.train_duration_sec
    forecast_mask = scenario_times_sec >= config.train_duration_sec
    num_train = int(np.sum(train_mask))
    if config.model_name == "narx":
        required_train = max(config.narx_input_lags, config.narx_feedback_lags) + 1
        if num_train < required_train:
            raise ValueError(
                "Training sequence is too short for the chosen NARX delays. "
                f"num_train={num_train}, narx_input_lags={config.narx_input_lags}, "
                f"narx_feedback_lags={config.narx_feedback_lags}."
            )
    elif num_train <= config.input_len + config.pred_len:
        raise ValueError(
            "Training sequence is too short for the chosen input_len and pred_len. "
            f"num_train={num_train}, input_len={config.input_len}, pred_len={config.pred_len}."
        )

    log_section(logger, "Propagation")
    r_sgp4_eci_m, v_sgp4_eci_mps = propagate_sgp4_gcrf(
        line1=satellite.line1,
        line2=satellite.line2,
        sample_times_since_tle_sec=sample_times_since_tle_sec,
        chunk_size=config.sgp4_chunk_size,
        cache_dir=output_dirs["cache"],
        memmap_threshold_mb=config.memmap_threshold_mb,
        logger=logger,
    )
    tle_epoch_date = datetime_to_absolutedate(satellite.epoch_utc)
    initial_position_m, initial_velocity_mps = get_tle_epoch_state_gcrf(satellite.line1, satellite.line2)
    r_truth_eci_m, v_truth_eci_mps = propagate_orekit_truth(
        initial_position_m=initial_position_m,
        initial_velocity_mps=initial_velocity_mps,
        sample_times_since_tle_sec=sample_times_since_tle_sec,
        initial_date=tle_epoch_date,
        config=config,
        cache_dir=output_dirs["cache"],
        logger=logger,
    )

    c_eci_to_rtn = build_eci_to_rtn_matrices(r_sgp4_eci_m, v_sgp4_eci_mps)
    clean_delta_r_eci_m = r_truth_eci_m - r_sgp4_eci_m
    clean_delta_v_eci_mps = v_truth_eci_mps - v_sgp4_eci_mps
    clean_delta_r_rtn_m = project_batch_eci_to_rtn(c_eci_to_rtn, clean_delta_r_eci_m)
    clean_delta_v_rtn_mps = project_batch_eci_to_rtn(c_eci_to_rtn, clean_delta_v_eci_mps)
    clean_target_full = combine_target(clean_delta_r_rtn_m, clean_delta_v_rtn_mps, config.predict_velocity)
    if config.predict_velocity:
        logger.info("Learning target: RTN residuals [R, T, N, Vr, Vt, Vn].")
    else:
        logger.info("Learning target: RTN position residuals [R, T, N].")

    log_section(logger, "Synthetic Observations")
    observation_bundle = make_noisy_training_observations(
        config=config,
        rng=rng,
        train_mask=train_mask,
        c_eci_to_rtn=c_eci_to_rtn,
        r_sgp4_eci_m=r_sgp4_eci_m,
        v_sgp4_eci_mps=v_sgp4_eci_mps,
        r_hpop_eci_m=r_truth_eci_m,
        v_hpop_eci_mps=v_truth_eci_mps,
        clean_pos_rtn=clean_delta_r_rtn_m,
        clean_vel_rtn=clean_delta_v_rtn_mps,
    )

    if config.model_name == "narx":
        model_inputs_full = build_narx_exogenous_features(
            r_sgp4_eci_m=r_sgp4_eci_m,
            v_sgp4_eci_mps=v_sgp4_eci_mps,
            include_velocity=config.narx_use_velocity_input,
        )
        model_inputs_train = model_inputs_full[train_mask]
        scalers = fit_narx_scalers(
            exogenous_inputs_train=model_inputs_train,
            target_train=observation_bundle.clean_target,
        )
        dataset = NARXWindowDataset(
            exogenous_inputs=scalers["narx_input"].transform(model_inputs_train),
            feedback_series=scalers["target"].transform(observation_bundle.noisy_target),
            targets=scalers["target"].transform(observation_bundle.clean_target),
            input_lags=config.narx_input_lags,
            feedback_lags=config.narx_feedback_lags,
            stride=config.window_stride,
        )
        train_eval_start = max(config.narx_input_lags, config.narx_feedback_lags)
    else:
        orbital_period_sec = estimate_orbital_period_sec(r_sgp4_eci_m[0], v_sgp4_eci_mps[0])
        static_features_full = build_static_features(
            times_sec=scenario_times_sec,
            r_sgp4_eci_m=r_sgp4_eci_m,
            v_sgp4_eci_mps=v_sgp4_eci_mps,
            orbital_period_sec=orbital_period_sec,
        )
        static_features_train = static_features_full[train_mask]
        history_features_train = build_history_features(static_features_train, observation_bundle.noisy_target)
        scalers = fit_scalers(
            history_features_train=history_features_train,
            future_covariates_train=static_features_train,
            target_train=observation_bundle.clean_target,
        )
        scalers["input_len"] = config.input_len

        dataset = SequenceWindowDataset(
            history_features=scalers["history"].transform(history_features_train),
            future_covariates=scalers["future"].transform(static_features_train),
            targets=scalers["target"].transform(observation_bundle.clean_target),
            input_len=config.input_len,
            pred_len=config.pred_len,
            stride=config.window_stride,
        )
        train_eval_start = config.input_len

    log_section(logger, "Training")
    train_result = train_model(dataset=dataset, config=config, models_dir=output_dirs["models"], logger=logger)
    if config.model_name == "narx":
        train_pred_target = narx_teacher_forced_rollout(
            model=train_result.model,
            device=train_result.device,
            exogenous_inputs=model_inputs_train,
            feedback_series=observation_bundle.noisy_target,
            config=config,
            scalers=scalers,
        )
    else:
        train_pred_target = seq2seq_teacher_forced_train_rollout(
            model=train_result.model,
            device=train_result.device,
            static_train=static_features_train,
            noisy_target_train=observation_bundle.noisy_target,
            config=config,
            scalers=scalers,
        )

    full_seed_target = np.zeros_like(clean_target_full)
    full_seed_target[train_mask] = observation_bundle.noisy_target
    log_section(logger, "Forecast Rollout")
    if config.model_name == "narx":
        predicted_target_full = narx_autoregressive_rollout(
            model=train_result.model,
            device=train_result.device,
            exogenous_inputs_full=model_inputs_full,
            feedback_seed_full=full_seed_target,
            forecast_start_index=num_train,
            config=config,
            scalers=scalers,
            logger=logger,
        )
    else:
        predicted_target_full = autoregressive_rollout(
            model=train_result.model,
            device=train_result.device,
            static_features_full=static_features_full,
            residual_history_full=full_seed_target,
            forecast_start_index=num_train,
            pred_len=config.pred_len,
            scalers=scalers,
            logger=logger,
        )

    pred_pos_rtn_full, pred_vel_rtn_full = split_target(predicted_target_full, config.predict_velocity)
    corrected_r_eci_m = r_sgp4_eci_m + project_batch_rtn_to_eci(c_eci_to_rtn, pred_pos_rtn_full)
    if config.predict_velocity:
        corrected_v_eci_mps = v_sgp4_eci_mps + project_batch_rtn_to_eci(c_eci_to_rtn, pred_vel_rtn_full)
    else:
        corrected_v_eci_mps = np.array(v_sgp4_eci_mps, copy=True)

    baseline_error_rtn_m = -clean_delta_r_rtn_m
    corrected_error_rtn_m = pred_pos_rtn_full - clean_delta_r_rtn_m
    baseline_error_norm_m = np.linalg.norm(r_sgp4_eci_m - r_truth_eci_m, axis=1)
    corrected_error_norm_m = np.linalg.norm(corrected_r_eci_m - r_truth_eci_m, axis=1)

    train_truth_eval = observation_bundle.clean_target[train_eval_start:]
    train_pred_eval = train_pred_target[train_eval_start:]
    train_truth_pos, train_truth_vel = split_target(train_truth_eval, config.predict_velocity)
    train_pred_pos, train_pred_vel = split_target(train_pred_eval, config.predict_velocity)

    forecast_truth_pos = clean_delta_r_rtn_m[forecast_mask]
    forecast_pred_pos = pred_pos_rtn_full[forecast_mask]
    zero_baseline_pos = np.zeros_like(forecast_truth_pos)
    baseline_rtn_metrics = component_metrics(forecast_truth_pos, zero_baseline_pos, COMPONENT_LABELS_POS)
    corrected_rtn_metrics = component_metrics(forecast_truth_pos, forecast_pred_pos, COMPONENT_LABELS_POS)
    baseline_3d_rmse = float(np.sqrt(np.mean(baseline_error_norm_m[forecast_mask] ** 2)))
    corrected_3d_rmse = float(np.sqrt(np.mean(corrected_error_norm_m[forecast_mask] ** 2)))

    metrics = {
        "metadata": {
            "satellite_name": satellite.name,
            "norad_id": satellite.norad_id,
            "tle_epoch_utc": satellite.epoch_utc.isoformat(),
            "scenario_start_utc": scenario_start_utc.isoformat(),
            "common_inertial_frame": "GCRF",
            "learning_target_frame": "RTN",
            "learning_target_components": (
                ["R", "T", "N", "Vr", "Vt", "Vn"]
                if config.predict_velocity
                else ["R", "T", "N"]
            ),
            "orekit_data_path": orekit_context["data_path"],
            "synthetic_truth_note": "Orekit numerical truth is initialized from the TLE-epoch SGP4 Cartesian state and is not a real observed truth orbit.",
            "truth_force_models": {
                "gravity_degree": config.orekit_gravity_degree,
                "gravity_order": config.orekit_gravity_order,
                "third_body": config.orekit_enable_third_body,
                "drag_nrlmsise00": config.orekit_enable_drag,
                "srp": config.orekit_enable_srp,
                "relativity": config.orekit_enable_relativity,
            },
        },
        "train_segment": {
            "prediction_start_sec": float(scenario_times_sec[train_eval_start]),
            "position_rtn": component_metrics(train_truth_pos, train_pred_pos, COMPONENT_LABELS_POS),
        },
        "forecast_segment": {
            "baseline_rtn": baseline_rtn_metrics,
            "corrected_rtn": corrected_rtn_metrics,
            "baseline_3d_position_rmse_m": baseline_3d_rmse,
            "corrected_3d_position_rmse_m": corrected_3d_rmse,
            "baseline_final_position_error_m": float(baseline_error_norm_m[forecast_mask][-1]),
            "corrected_final_position_error_m": float(corrected_error_norm_m[forecast_mask][-1]),
            "improvement_percent_3d_rmse": improvement_percentage(baseline_3d_rmse, corrected_3d_rmse),
            "directional_improvement_percent": {
                axis: improvement_percentage(baseline_rtn_metrics[axis]["rmse"], corrected_rtn_metrics[axis]["rmse"])
                for axis in COMPONENT_LABELS_POS
            },
            "checkpoints": checkpoint_error_summary(
                times_sec=scenario_times_sec[forecast_mask],
                baseline_error_rtn=baseline_error_rtn_m[forecast_mask],
                corrected_error_rtn=corrected_error_rtn_m[forecast_mask],
                checkpoints_sec=[400.0, 1000.0, 5000.0, 10000.0, 36000.0],
            ),
        },
    }
    if config.predict_velocity and train_truth_vel is not None and train_pred_vel is not None:
        metrics["train_segment"]["velocity_rtn"] = component_metrics(train_truth_vel, train_pred_vel, COMPONENT_LABELS_VEL)
        forecast_truth_vel = clean_delta_v_rtn_mps[forecast_mask]
        forecast_pred_vel = pred_vel_rtn_full[forecast_mask]
        metrics["forecast_segment"]["baseline_velocity_rtn"] = component_metrics(
            forecast_truth_vel,
            np.zeros_like(forecast_truth_vel),
            COMPONENT_LABELS_VEL,
        )
        metrics["forecast_segment"]["corrected_velocity_rtn"] = component_metrics(
            forecast_truth_vel,
            forecast_pred_vel,
            COMPONENT_LABELS_VEL,
        )

    log_section(logger, "Saving Outputs")
    save_json(config.to_dict(), os.path.join(output_dirs["root"], "used_config.json"))
    if config.model_name == "narx":
        scaler_payload = {
            "narx_input": scalers["narx_input"].to_dict(),
            "target": scalers["target"].to_dict(),
        }
    else:
        scaler_payload = {
            "history": scalers["history"].to_dict(),
            "future": scalers["future"].to_dict(),
            "target": scalers["target"].to_dict(),
        }
    save_json(scaler_payload, os.path.join(output_dirs["data"], "scaler.json"))
    save_npz(
        os.path.join(output_dirs["data"], "sgp4_states.npz"),
        t_sec=scenario_times_sec,
        r_eci_m=np.asarray(r_sgp4_eci_m),
        v_eci_mps=np.asarray(v_sgp4_eci_mps),
    )
    save_npz(
        os.path.join(output_dirs["data"], "hpop_states.npz"),
        t_sec=scenario_times_sec,
        r_eci_m=np.asarray(r_truth_eci_m),
        v_eci_mps=np.asarray(v_truth_eci_mps),
    )
    save_state_dataframe(
        scenario_times_sec,
        np.asarray(r_sgp4_eci_m),
        np.asarray(v_sgp4_eci_mps),
        os.path.join(output_dirs["data"], "sgp4_states.csv"),
        float_format=config.csv_float_format,
    )
    save_state_dataframe(
        scenario_times_sec,
        np.asarray(r_truth_eci_m),
        np.asarray(v_truth_eci_mps),
        os.path.join(output_dirs["data"], "hpop_states.csv"),
        float_format=config.csv_float_format,
    )
    save_state_dataframe(
        scenario_times_sec,
        np.asarray(corrected_r_eci_m),
        np.asarray(corrected_v_eci_mps),
        os.path.join(output_dirs["data"], "corrected_states.csv"),
        float_format=config.csv_float_format,
    )
    save_residual_dataframe(
        scenario_times_sec,
        np.asarray(clean_delta_r_rtn_m),
        np.asarray(clean_delta_v_rtn_mps) if config.predict_velocity else None,
        os.path.join(output_dirs["data"], "residual_clean.csv"),
        float_format=config.csv_float_format,
    )
    noisy_pos_train, noisy_vel_train = split_target(observation_bundle.noisy_target, config.predict_velocity)
    save_residual_dataframe(
        scenario_times_sec[train_mask],
        noisy_pos_train,
        noisy_vel_train,
        os.path.join(output_dirs["data"], "residual_noisy_train.csv"),
        float_format=config.csv_float_format,
    )
    save_json(metrics, os.path.join(output_dirs["metrics"], "metrics.json"))
    save_metrics_csv(metrics, os.path.join(output_dirs["metrics"], "metrics.csv"))

    plot_3d_orbits(np.asarray(r_sgp4_eci_m), np.asarray(r_truth_eci_m), os.path.join(output_dirs["figures"], "orbit_3d.png"))
    plot_rtn_residuals(scenario_times_sec, np.asarray(clean_delta_r_rtn_m), os.path.join(output_dirs["figures"], "residual_clean_rtn.png"))
    plot_noisy_vs_clean_train(
        scenario_times_sec[train_mask],
        np.asarray(clean_delta_r_rtn_m[train_mask]),
        noisy_pos_train,
        os.path.join(output_dirs["figures"], "train_noisy_vs_clean.png"),
    )
    plot_training_history(train_result.history, os.path.join(output_dirs["figures"], "training_curves.png"))
    plot_forecast_residuals(
        scenario_times_sec[forecast_mask],
        forecast_truth_pos,
        forecast_pred_pos,
        os.path.join(output_dirs["figures"], "forecast_residuals.png"),
    )
    plot_error_comparison(
        scenario_times_sec[forecast_mask],
        baseline_error_norm_m[forecast_mask],
        corrected_error_norm_m[forecast_mask],
        os.path.join(output_dirs["figures"], "baseline_vs_corrected_error.png"),
    )
    plot_rmse_over_time(
        scenario_times_sec[forecast_mask],
        cumulative_vector_rmse(r_sgp4_eci_m[forecast_mask] - r_truth_eci_m[forecast_mask]),
        cumulative_vector_rmse(corrected_r_eci_m[forecast_mask] - r_truth_eci_m[forecast_mask]),
        os.path.join(output_dirs["figures"], "rmse_over_time.png"),
    )
    plot_final_error_bar(
        baseline_final_m=float(baseline_error_norm_m[forecast_mask][-1]),
        corrected_final_m=float(corrected_error_norm_m[forecast_mask][-1]),
        path=os.path.join(output_dirs["figures"], "final_error_bar.png"),
    )

    log_section(logger, "Summary")
    logger.info("Train position RTN RMSE [m]: %s", {axis: metrics["train_segment"]["position_rtn"][axis]["rmse"] for axis in COMPONENT_LABELS_POS})
    logger.info("Forecast baseline 3D RMSE [m]: %.6f", baseline_3d_rmse)
    logger.info("Forecast corrected 3D RMSE [m]: %.6f", corrected_3d_rmse)
    logger.info("Forecast improvement [%%]: %.3f", metrics["forecast_segment"]["improvement_percent_3d_rmse"])
    logger.info("Outputs saved under: %s", os.path.abspath(output_dirs["root"]))


if __name__ == "__main__":
    main()
