"""Precompute and reload scenario data for repeated trials."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from typing import Any, Optional

import numpy as np

from data.preprocess import (
    ObservationBundle,
    build_time_grid,
    combine_target,
    make_noisy_training_observations,
)
from orbit.frames import datetime_to_absolutedate, initialize_orekit
from orbit.hpop_prop import propagate_orekit_truth
from orbit.rtn import build_eci_to_rtn_matrices, project_batch_eci_to_rtn
from orbit.sgp4_prop import get_tle_epoch_state_gcrf, propagate_sgp4_gcrf
from orbit.tle_io import load_tle_satellite


PRECOMPUTE_SIGNATURE_FIELDS = [
    "tle_file",
    "sat_name",
    "scenario_start_utc",
    "orekit_data_path",
    "receiver_lat_deg",
    "receiver_lon_deg",
    "receiver_alt_m",
    "train_duration_sec",
    "total_duration_sec",
    "dt_train_sec",
    "dt_full_sec",
    "sgp4_chunk_size",
    "hpop_chunk_size",
    "observation_mode",
    "predict_velocity",
    "noise_sigma_r_m",
    "noise_sigma_t_m",
    "noise_sigma_n_m",
    "noise_sigma_vr_mps",
    "noise_sigma_vt_mps",
    "noise_sigma_vn_mps",
    "seed",
    "orekit_mass_kg",
    "orekit_drag_cd",
    "orekit_drag_area_m2",
    "orekit_srp_cr",
    "orekit_srp_area_m2",
    "orekit_gravity_degree",
    "orekit_gravity_order",
    "orekit_enable_third_body",
    "orekit_enable_drag",
    "orekit_enable_srp",
    "orekit_enable_relativity",
    "orekit_solar_activity_level",
    "orekit_min_step_sec",
    "orekit_max_step_sec",
    "orekit_abs_tolerance",
    "orekit_rel_tolerance",
]


def parse_utc_datetime(value: Optional[str]) -> Optional[datetime]:
    """Parse a UTC datetime string into a timezone-aware datetime."""
    if value is None:
        return None
    text = value.strip().replace("Z", "+00:00")
    dt = datetime.fromisoformat(text)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt


def _normalize_signature_value(key: str, value: Any) -> Any:
    """Normalize config values before storing them in the bundle signature."""
    if key.endswith("_file") or key.endswith("_path"):
        return None if value is None else os.path.abspath(str(value))
    return value


def build_precompute_signature(config) -> dict[str, Any]:
    """Create the config signature for cache validation."""
    signature = {}
    for key in PRECOMPUTE_SIGNATURE_FIELDS:
        signature[key] = _normalize_signature_value(key, getattr(config, key))
    return signature


def build_scenario_bundle(config, cache_dir: str, logger) -> dict[str, Any]:
    """Precompute the propagation, RTN residuals, and noisy observations once."""
    rng = np.random.default_rng(config.seed)

    logger.info("Preparing scenario bundle from propagation outputs.")
    orekit_context = initialize_orekit(config.orekit_data_path, logger=logger)
    logger.info("TLE initializes the nominal SGP4 orbit through Orekit TLEPropagator.")
    logger.info("Synthetic truth is generated by Orekit NumericalPropagator, initialized from the TLE-epoch SGP4 Cartesian state.")
    logger.info("This synthetic truth is not a real measurement truth orbit.")
    logger.info("All trajectory comparisons are performed in the common inertial frame GCRF.")
    logger.info("Orekit data source: %s", orekit_context["data_path"])
    logger.info(
        "Receiver LLA metadata: lat=%.6f deg, lon=%.6f deg, alt=%.3f m. Current observation model does not enforce station visibility.",
        config.receiver_lat_deg,
        config.receiver_lon_deg,
        config.receiver_alt_m,
    )

    satellite = load_tle_satellite(config.tle_file, config.sat_name)
    scenario_start_utc = parse_utc_datetime(config.scenario_start_utc) or satellite.epoch_utc
    if scenario_start_utc < satellite.epoch_utc:
        raise ValueError(
            f"scenario_start_utc ({scenario_start_utc.isoformat()}) must not be earlier than TLE epoch ({satellite.epoch_utc.isoformat()})."
        )
    scenario_offset_sec = (scenario_start_utc - satellite.epoch_utc).total_seconds()
    logger.info(
        "Satellite: %s | NORAD: %s | TLE epoch UTC: %s | Scenario start UTC: %s",
        satellite.name,
        satellite.norad_id,
        satellite.epoch_utc.isoformat(),
        scenario_start_utc.isoformat(),
    )

    scenario_times_sec = build_time_grid(
        train_duration_sec=config.train_duration_sec,
        total_duration_sec=config.total_duration_sec,
        dt_train_sec=config.dt_train_sec,
        dt_full_sec=config.dt_full_sec,
    )
    sample_times_since_tle_sec = scenario_offset_sec + scenario_times_sec
    train_mask = scenario_times_sec < config.train_duration_sec

    r_sgp4_eci_m, v_sgp4_eci_mps = propagate_sgp4_gcrf(
        line1=satellite.line1,
        line2=satellite.line2,
        sample_times_since_tle_sec=sample_times_since_tle_sec,
        chunk_size=config.sgp4_chunk_size,
        cache_dir=cache_dir,
        memmap_threshold_mb=config.memmap_threshold_mb,
        logger=logger,
    )
    tle_epoch_date = datetime_to_absolutedate(satellite.epoch_utc)
    initial_position_m, initial_velocity_mps = get_tle_epoch_state_gcrf(satellite.line1, satellite.line2)
    r_truth_eci_m, v_truth_eci_mps = propagate_orekit_truth(
        initial_position_m=initial_position_m,
        initial_velocity_mps=initial_velocity_mps,
        sample_times_since_tle_sec=sample_times_since_tle_sec,
        initial_date=tle_epoch_date,
        config=config,
        cache_dir=cache_dir,
        logger=logger,
    )

    c_eci_to_rtn = build_eci_to_rtn_matrices(r_sgp4_eci_m, v_sgp4_eci_mps)
    clean_delta_r_eci_m = r_truth_eci_m - r_sgp4_eci_m
    clean_delta_v_eci_mps = v_truth_eci_mps - v_sgp4_eci_mps
    clean_delta_r_rtn_m = project_batch_eci_to_rtn(c_eci_to_rtn, clean_delta_r_eci_m)
    clean_delta_v_rtn_mps = project_batch_eci_to_rtn(c_eci_to_rtn, clean_delta_v_eci_mps)

    observation_bundle = make_noisy_training_observations(
        config=config,
        rng=rng,
        train_mask=train_mask,
        c_eci_to_rtn=c_eci_to_rtn,
        r_sgp4_eci_m=r_sgp4_eci_m,
        v_sgp4_eci_mps=v_sgp4_eci_mps,
        r_hpop_eci_m=r_truth_eci_m,
        v_hpop_eci_mps=v_truth_eci_mps,
        clean_pos_rtn=clean_delta_r_rtn_m,
        clean_vel_rtn=clean_delta_v_rtn_mps,
    )

    metadata = {
        "signature": build_precompute_signature(config),
        "satellite_name": satellite.name,
        "norad_id": satellite.norad_id,
        "tle_epoch_utc": satellite.epoch_utc.isoformat(),
        "scenario_start_utc": scenario_start_utc.isoformat(),
        "common_inertial_frame": "GCRF",
        "orekit_data_path": orekit_context["data_path"],
        "synthetic_truth_note": "Orekit numerical truth is initialized from the TLE-epoch SGP4 Cartesian state and is not a real observed truth orbit.",
        "truth_force_models": {
            "gravity_degree": config.orekit_gravity_degree,
            "gravity_order": config.orekit_gravity_order,
            "third_body": config.orekit_enable_third_body,
            "drag_nrlmsise00": config.orekit_enable_drag,
            "srp": config.orekit_enable_srp,
            "relativity": config.orekit_enable_relativity,
        },
    }

    return {
        "metadata": metadata,
        "scenario_times_sec": np.asarray(scenario_times_sec),
        "train_mask": np.asarray(train_mask),
        "r_sgp4_eci_m": np.asarray(r_sgp4_eci_m),
        "v_sgp4_eci_mps": np.asarray(v_sgp4_eci_mps),
        "r_truth_eci_m": np.asarray(r_truth_eci_m),
        "v_truth_eci_mps": np.asarray(v_truth_eci_mps),
        "clean_delta_r_rtn_m": np.asarray(clean_delta_r_rtn_m),
        "clean_delta_v_rtn_mps": np.asarray(clean_delta_v_rtn_mps),
        "clean_target_train": np.asarray(observation_bundle.clean_target),
        "noisy_target_train": np.asarray(observation_bundle.noisy_target),
    }


def save_scenario_bundle(bundle: dict[str, Any], path: str) -> None:
    """Serialize a precomputed bundle into a compressed NPZ."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    arrays = {key: value for key, value in bundle.items() if key != "metadata"}
    arrays["metadata_json"] = np.asarray(json.dumps(bundle["metadata"], ensure_ascii=False))
    np.savez_compressed(path, **arrays)


def load_scenario_bundle(path: str) -> dict[str, Any]:
    """Load a precomputed bundle from NPZ."""
    with np.load(path, allow_pickle=False) as payload:
        metadata = json.loads(str(payload["metadata_json"].item()))
        bundle = {"metadata": metadata}
        for key in payload.files:
            if key == "metadata_json":
                continue
            bundle[key] = payload[key]
    return bundle


def validate_scenario_bundle(bundle: dict[str, Any], config) -> None:
    """Ensure a loaded bundle matches the current scenario setup."""
    expected = build_precompute_signature(config)
    actual = bundle["metadata"]["signature"]
    mismatches = []
    for key, expected_value in expected.items():
        if actual.get(key) != expected_value:
            mismatches.append((key, actual.get(key), expected_value))
    if mismatches:
        preview = ", ".join(f"{key}: bundle={got!r}, current={want!r}" for key, got, want in mismatches[:5])
        raise ValueError(f"Precomputed bundle does not match the current scenario configuration. Mismatches: {preview}")


def build_observation_bundle_from_precomputed(bundle: dict[str, Any], predict_velocity: bool) -> ObservationBundle:
    """Reconstruct the observation bundle object from a precomputed bundle."""
    noisy_target = np.asarray(bundle["noisy_target_train"])
    clean_target = np.asarray(bundle["clean_target_train"])
    if predict_velocity:
        noisy_pos = noisy_target[:, :3]
        noisy_vel = noisy_target[:, 3:]
    else:
        noisy_pos = noisy_target[:, :3]
        noisy_vel = None
    return ObservationBundle(
        clean_target=clean_target,
        noisy_target=noisy_target,
        noisy_pos_rtn=noisy_pos,
        noisy_vel_rtn=noisy_vel,
    )


def load_or_build_scenario_bundle(config, cache_dir: str, logger) -> dict[str, Any]:
    """Load a precomputed bundle if provided, otherwise build it from scratch."""
    if config.precomputed_bundle_path:
        logger.info("Loading precomputed scenario bundle: %s", os.path.abspath(config.precomputed_bundle_path))
        bundle = load_scenario_bundle(config.precomputed_bundle_path)
        validate_scenario_bundle(bundle, config)
        logger.info("Loaded precomputed scenario bundle successfully.")
        return bundle
    return build_scenario_bundle(config=config, cache_dir=cache_dir, logger=logger)
